# Dependencies
gems: 		[jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Frank Blandon
tagline:          'Programmer'
description:      'A developer from St Pete, Florida with a passion for tech, fishing, reading and killing flies.'
url:              http://blandonfrank.github.io/
baseurl:          

author:
  name:           'Frank Blandon'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:         https://github.com/blandonfrank
linkedin:	https://www.linkedin.com/in/frank-blandon-99900516
